# Generated by Django 4.2 on 2023-04-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "course_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("credits", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="department",
            fields=[
                (
                    "department_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "student_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=15)),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="faculty",
            fields=[
                (
                    "faculty_id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=15)),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="enrollment",
            fields=[
                (
                    "enrollment_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "grade",
                    models.TextField(
                        choices=[
                            ("EX", "EX"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("P", "P"),
                            ("F", "F"),
                        ]
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.course"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="course_dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.department"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="faculty_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.faculty"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student_id", "course_id"), name="unique_student_course"
            ),
        ),
    ]
